server:
  jsp-servlet:
    init-parameters:
      development: true

spring:
  config:
    import:
      - application-test-gemini.yml
  application:
    name: flashnote
  web:
    resources:
      static-locations: classpath:/static/,classpath:/public/,classpath:/resources/
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  jpa:
    properties:
      hibernate:
        jdbc.batch_size: 50
        order_inserts: true
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
    locations:
      - classpath:db/migration/test
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: dummy-id
            client-secret: dummy-secret
            scope:
              - openid
              - email
